vapor-community/HTMLKit

Sources/HTMLKit/Localize.swift, Sources/HTMLKit/View Builders/TemplateBuilder.swift, Tests/HTMLKitTests/HTMLTestDocuments.swift
The Main tag seems to miss. Since it is still an official html 5 tag, I added it to the TemplateBuilder.
There was I misspelling in the Localize file, wich came to my attention.
=> Add missing tag and fix typo

README.md, Sources/HTMLKit/View Builders/TemplateBuilder.swift
I forgot to correct the .environment spelling in the Readme file in the first place, so I changed it now. Also I corrected the spelling accordingly the issues #26 and changed it in the Readme file either. 
I have added the missing option "reset" for the Button tag.
The Audio tag hadn't the right tag name yet.
=> Correct spelling, add missing case and fix a html tag

.github/workflows/swift.yml, Package.swift, Sources/HTMLKit/External/Elements/BasicElements.swift, Sources/HTMLKit/External/Elements/BodyElements.swift, Sources/HTMLKit/External/Elements/DefinitionElements.swift, Sources/HTMLKit/External/Elements/FigureElements.swift, Sources/HTMLKit/External/Elements/FormElements.swift, Sources/HTMLKit/External/Elements/HeadElements.swift, Sources/HTMLKit/External/Elements/HtmlElements.swift, Sources/HTMLKit/External/Elements/InputElements.swift, Sources/HTMLKit/External/Elements/ListElements.swift, Sources/HTMLKit/External/Elements/MapElements.swift, Sources/HTMLKit/External/Elements/MediaElements.swift, Sources/HTMLKit/External/Elements/ObjectElements.swift, Sources/HTMLKit/External/Elements/RubyElements.swift, Sources/HTMLKit/External/Elements/TableElements.swift, Sources/HTMLKit/Internal/Core/Builders/StringBuilder.swift, Sources/HTMLKit/Internal/Core/Elements.swift, Sources/HTMLKit/Internal/Core/Properties/Modifiable.swift, Sources/HTMLKit/Internal/Features/Conversion/Converter.swift, Sources/HTMLKit/Internal/Features/Conversion/Stencils.swift, Tests/HTMLKitTests/Conversion/articles/article.html, Tests/HTMLKitTests/Conversion/index.html, Tests/HTMLKitTests/ConversionTests.swift, Tests/HTMLKitTests/RenderingTests.swift, Tests/LinuxMain.swift
This merge will bring back the modifier for optional values and it also adds a converter for HTML to HTMLKit.
```swift
let converter = Converter()
```
The converter has two methods. One for a directory and the other for a specific file.
```swift
/// goes through a directory and converts every file with the extension ".html"
convert(directory: URL, fileExtension: Extension = .html, option: Output)
/// converts the file
convert(file: URL, option: Output)
```
```swift 
public enum Extension: String {
case html
case leaf
}
```
The case `leaf` is for later, when the implementation for Leaf is done.
```swift
public enum Output: String {
case print
case file
}
```
Choose the case `print` first, to get sure everything will converted correctly. The output shows up in your console.
There could be …
=> Implement a converter

Sources/HTMLKit/External/Types.swift
This PR proposes to introduce the `rel="external"` attribute value, which indicates that the referenced document is not part of the same site as the current document.
=> Add support for rel=“external”

Sources/HTMLKit/External/Attributes/VectorAttributes.swift, Sources/HTMLKit/External/Elements/VectorElements.swift
This PR proposes support for the SVG `<path d="…">` attribute, as described here: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d
=> Add support for the SVG <path d=“…”> attribute

Sources/HTMLKit/External/Attributes/AriaAttributes.swift, Sources/HTMLKit/External/Elements/BodyElements.swift, Sources/HTMLKit/External/Elements/DefinitionElements.swift, Sources/HTMLKit/External/Elements/FigureElements.swift, Sources/HTMLKit/External/Elements/FormElements.swift, Sources/HTMLKit/External/Elements/HtmlElements.swift, Sources/HTMLKit/External/Elements/InputElements.swift, Sources/HTMLKit/External/Elements/ListElements.swift, Sources/HTMLKit/External/Elements/MapElements.swift, Sources/HTMLKit/External/Elements/RubyElements.swift, Sources/HTMLKit/External/Elements/TableElements.swift, Sources/HTMLKit/External/Types.swift, Tests/HTMLKitTests/AttributesTests.swift
This merge will fix the issue #90.
It adds support for aria attributes. 
Example:
```swift 
Body {
}
.aria(hasPopup: .grid)
```
Result:
```html 
<body aria-haspopup="grid"></body>
```
=> Add support for the aria attributes

Sources/HTMLKit/Internal/Features/Conversion/Converter.swift, Tests/HTMLKitTests/Conversion/index.html
This merge will update the converter to support the event and aria attributes, wich were lately introduced into HTMLKit. The converter couldn't dissolve the syntax of the attributes yet since there is a slightly difference. Therefore I had to make changes to the `ValueProperty<T>` and `TypeProperty<T>` and introduce `EventProperty`.
Also it adds the element `g` (Group) and the attribute `d` (draw) to the converter. Both were introduced in the pull request #82.
=> Update the converter to support event and aria attributes

Package.swift
I forgot to make the converter available. The merge adds the plugin as a product of the package and makes it available to use.
=> Make the converter available to use

Package.swift, Sources/HTMLKitVaporProvider/Extensions/Vapor+HTMLKit.swift, Sources/HTMLKitVaporProvider/VaporCache.swift, Sources/HTMLKitVaporProvider/VaporRenderer.swift, Tests/HTMLKitVaporProviderTests/ProviderTests.swift
This merge adjusts the provider to the latest changes. There has been an overlap of the latest pull requests.
=> Adjust the vapor provider

Sources/HTMLKit/Framework/Environment/Statements/BranchStatements.swift, Tests/HTMLKitTests/StatementsTests.swift
This merge will fix the issue #108.
=> Fix conditional statement

Sources/HTMLKit/Abstraction/Elements/HeadElements.swift, Sources/HTMLKit/Framework/Builders/ContentBuilder.swift, Tests/HTMLKitTests/StatementTests.swift
This PR proposes to update the ContentBuilder to support partial blocks. This seems to resolve the issues that I was seeing with #132, and potentially other unexpectedly invalid content combinations.
Sorry for the lack of comment documentation on these revised methods. 
I've also included conformance of the `Link` type to `BodyElement` as it's valid HTML.
=> Result builder fixes

Sources/HTMLKit/Abstraction/Attributes/BasicAttributes.swift, Sources/HTMLKit/Abstraction/Elements/BasicElements.swift, Sources/HTMLKit/Abstraction/Elements/BodyElements.swift, Sources/HTMLKit/Abstraction/Elements/DefinitionElements.swift, Sources/HTMLKit/Abstraction/Elements/FigureElements.swift, Sources/HTMLKit/Abstraction/Elements/FormElements.swift, Sources/HTMLKit/Abstraction/Elements/HeadElements.swift, Sources/HTMLKit/Abstraction/Elements/HtmlElements.swift, Sources/HTMLKit/Abstraction/Elements/InputElements.swift, Sources/HTMLKit/Abstraction/Elements/ListElements.swift, Sources/HTMLKit/Abstraction/Elements/MapElements.swift, Sources/HTMLKit/Abstraction/Elements/MediaElements.swift, Sources/HTMLKit/Abstraction/Elements/ObjectElements.swift, Sources/HTMLKit/Abstraction/Elements/RubyElements.swift, Sources/HTMLKit/Abstraction/Elements/TableElements.swift, Sources/HTMLKit/Framework/Environment/EnvironmentValue.swift, Sources/HTMLKit/Framework/Extensions/Datatypes+Content.swift, Sources/HTMLKit/Framework/Primitives/Nodes/Nodes.swift, Sources/HTMLKit/Framework/Rendering/Renderer.swift, Tests/HTMLKitTests/AttributesTests.swift, Tests/HTMLKitTests/EnvironmentTests.swift
This merge tackles the latest ideas and issues (#134, #138).
In the past you had to use the modify method to alter an attribute for an element based on a condition.
```swift
Input()
.modify(if: true) {
$0.checked()
}
```
Now you can use the condition on the attribute with the same result.
```swift
Input()
.checked(true)
```
Keep in mind not every attribute has a conditional option for now. I have added it to attributes, where I think it makes  the most sense. If you find an attribute in the future, where you think it makes sense, let me know. 
The modify method still exists. I am thinking about to remove it as we can use an `if let` to unwrap an optional too, but thats a topic for a different time.
You can now pass an environment value to an attribute. Currently it is only available for …
=> Upgrade the package

Sources/HTMLKit/Framework/Rendering/Renderer.swift, Sources/HTMLKit/Framework/Security/Security.swift, Sources/HTMLKitComponents/Actions/SubmitAction.swift, Sources/HTMLKitComponents/Actions/ViewAction.swift, Sources/HTMLKitComponents/Extensions/Components+String.swift, Sources/HTMLKitVapor/Extensions/Vapor+HTMLKit.swift, Sources/HTMLKitVapor/ViewRenderer.swift, Tests/HTMLKitComponentsTests/SecurityTests.swift, Tests/HTMLKitTests/PerformanceTests.swift, Tests/HTMLKitTests/RenderingTests.swift, Tests/HTMLKitTests/SecurityTests.swift
At the moment HTMLKit is vulnerable to arbitrary code insertions. This PR introduces auto escaping of string variables to mitigate (stored) cross site scripting. That said, this behavior will be on by default in the future.
But if you don't want to use the auto escape for any reasons, you can disabled it with the option:
```swift
app.htmlkit.security.autoEscaping = false
```
=> Harden the HTML output

Package.swift, Sources/HTMLKit/Framework/Localization/Locale.swift, Sources/HTMLKit/Framework/Localization/Localizable.swift, Sources/HTMLKit/Framework/Localization/Localization.swift, Sources/HTMLKit/Framework/Localization/LocalizedStringKey.swift, Sources/HTMLKit/Framework/Localization/TranslationTable.swift, Sources/HTMLKit/Framework/Rendering/Renderer.swift, Sources/HTMLKitVapor/Extensions/Vapor+HTMLKit.swift, Sources/HTMLKitVapor/ViewRenderer.swift, Tests/HTMLKitTests/LocalizationTests.swift, Tests/HTMLKitTests/PerformanceTests.swift
This pull request is the first of two addressing the issue #148. While the public API remains unchanged, it adds more precise error messages for better understanding during development and introduces a recovery mechanism for cases where a key is missing in one of the non-default translation tables.
=> Make localization error handling less strict

Sources/HTMLKit/Abstraction/Attributes/BasicAttributes.swift, Sources/HTMLKit/Abstraction/Elements/TableElements.swift, Sources/HTMLKit/Abstraction/Tokens/ValueTokens.swift, Tests/HTMLKitTests/AttributesTests.swift
The scope attribute is actually an enumerated attribute. Therefore the modifier should accept an enum. This pull request corrects that.
=> Make the scope modifier accept an enum

Sources/HTMLKit/Abstraction/Elements/MapElements.swift, Tests/HTMLKitTests/ElementTests.swift
The area element should have been an empty node from the start. This pull request corrects that.
=> Make area element an empty node

Sources/HTMLKit/Abstraction/Attributes/BasicAttributes.swift, Sources/HTMLKit/Abstraction/Elements/BodyElements.swift
The image element misses the ismap attribute. This pull request catches up on this.
=> Assign the ismap attribute

Sources/HTMLKit/Abstraction/Attributes/BasicAttributes.swift, Sources/HTMLKit/Abstraction/Elements/BasicElements.swift, Sources/HTMLKit/Abstraction/Elements/BodyElements.swift, Sources/HTMLKit/Abstraction/Elements/DefinitionElements.swift, Sources/HTMLKit/Abstraction/Elements/FigureElements.swift, Sources/HTMLKit/Abstraction/Elements/FormElements.swift, Sources/HTMLKit/Abstraction/Elements/HeadElements.swift, Sources/HTMLKit/Abstraction/Elements/HtmlElements.swift, Sources/HTMLKit/Abstraction/Elements/InputElements.swift, Sources/HTMLKit/Abstraction/Elements/ListElements.swift, Sources/HTMLKit/Abstraction/Elements/MapElements.swift, Sources/HTMLKit/Abstraction/Elements/MediaElements.swift, Sources/HTMLKit/Abstraction/Elements/ObjectElements.swift, Sources/HTMLKit/Abstraction/Elements/RubyElements.swift, Sources/HTMLKit/Abstraction/Elements/TableElements.swift, Sources/HTMLKit/Abstraction/Tokens/ValueTokens.swift, Tests/HTMLKitTests/AttributesTests.swift
The inputmode attribute is actually an enumerated attribute. Therefore the modifier should accept an enum. This pull request corrects that.
=> Make the inputmode modifier accept an enum 

Sources/HTMLKit/Abstraction/Elements/BodyElements.swift, Sources/HTMLKit/Abstraction/Elements/FormElements.swift, Sources/HTMLKit/Abstraction/Elements/TableElements.swift, Sources/HTMLKit/Framework/Localization/InterpolationArgument.swift, Sources/HTMLKit/Framework/Localization/Localizable.swift, Sources/HTMLKit/Framework/Localization/Localization.swift, Sources/HTMLKit/Framework/Localization/LocalizedString.swift, Sources/HTMLKit/Framework/Localization/LocalizedStringKey.swift, Sources/HTMLKit/Framework/Rendering/Renderer.swift, Sources/HTMLKitComponents/Components/Text.swift, Tests/HTMLKitTests/Localization/en-GB/mobile.strings, Tests/HTMLKitTests/Localization/en-GB/web.strings, Tests/HTMLKitTests/Localization/fr/web.strings, Tests/HTMLKitTests/LocalizationTests.swift, Tests/HTMLKitTests/PerformanceTests.swift, Tests/HTMLKitVaporTests/Localization/en-GB/mobile.strings, Tests/HTMLKitVaporTests/Localization/en-GB/web.strings, Tests/HTMLKitVaporTests/Localization/fr/web.strings, Tests/HTMLKitVaporTests/ProviderTests.swift
This pull request experiments with changing the interpolation for localization.
Instead of passing interpolation arguments through the parameter...
```swift
Heading1("greeting.person", interpolation: "John Doe")
```
...you will now be able to use string interpolation directly.
```swift
Heading1("Hello \("John Doe")")
```
Additionally the format specifiers have changed and now follows the "standard", so to say. While I find `%st`, `%do`, `%in` or `%dt` more straightforward, this change allows the reuse of existing string translations, maybe from an iOS app or similar.
```
"Hello %@" = "Hello %@";
```
So use `%@` for string values, `%lld` for int values, and `%f` for floating point values.
If someone mistakenly use the localization initializer without intending to use localization it …
=> Change localization interpolation

Sources/HTMLKit/Abstraction/Attributes/BasicAttributes.swift, Sources/HTMLKit/Abstraction/Elements/BodyElements.swift, Tests/HTMLKitTests/AttributesTests.swift
The pull request adds the missing usemap attribute.
=> Introduce the usemap attribute

Sources/HTMLKit/Framework/Localization/Localization.swift, Sources/HTMLKit/Framework/Rendering/Renderer.swift, Sources/HTMLKitVapor/Extensions/Vapor+HTMLKit.swift, Tests/HTMLKitVaporTests/ProviderTests.swift, Tests/HTMLKitVaporTests/Utilities/AbortResponse.swift
This pull request adds an additional fallback check to the rendering for the localization. Currently, the only check is whether the localization is initialized, which can result in a false positive because the Vapor provider initializes it during configuration. To address this, another check has been introduced to determine if the localization is intended for use, based on the configuration setter.
```swift
app.htmlkit.localization.set(source:)
app.htmlkit.localization.set(locale:)
```
It also prevents the default locale from being overridden. Currently, the default locale gets overridden by the client's accept language header through the provider, but the environment locale is the value that should actually be overridden instead.
=> Fix localization fallback behaviour

Sources/HTMLKit/Abstraction/Elements/BodyElements.swift, Tests/HTMLKitTests/ElementTests.swift
The tag for the variable element is incorrect. It should be `<var>` instead. The pull request fixes this.
=> Fix the incorrect tag for the variable element

Sources/HTMLKit/Abstraction/Elements/TableElements.swift, Tests/HTMLKitTests/ElementTests.swift
The column element should have been an empty node from the start. This pull request corrects that.
=> Make column element an empty node

Sources/HTMLKit/Abstraction/Attributes/BasicAttributes.swift, Sources/HTMLKit/Abstraction/Elements/BodyElements.swift, Sources/HTMLKit/Abstraction/Tokens/ValueTokens.swift, Tests/HTMLKitTests/AttributesTests.swift
The sandbox attribute is actually an enumerated attribute. However, the unique aspect here is that the attribute also allows a list of values. Therefore the modifier should accept either an enum or a set of options.
```swift
/// Restrict everything
InlineFrame {}.sandbox()
/// Restrict everything but downloads
InlineFrame {}.sandbox(.allowDownloads)
/// Permit popups and forms
InlineFrame {}.sandbox([.allowPopups, .allowForms])
```
=> Make the sandbox modifier accept an enum 

Sources/HTMLKit/Framework/Environment/Condition.swift, Sources/HTMLKit/Framework/Environment/Conditionable.swift, Sources/HTMLKit/Framework/Environment/Conditional.swift, Sources/HTMLKit/Framework/Environment/Environment.swift, Sources/HTMLKit/Framework/Environment/EnvironmentKeys.swift, Sources/HTMLKit/Framework/Environment/EnvironmentModifier.swift, Sources/HTMLKit/Framework/Environment/EnvironmentObject.swift, Sources/HTMLKit/Framework/Environment/EnvironmentString.swift, Sources/HTMLKit/Framework/Environment/EnvironmentValue.swift, Sources/HTMLKit/Framework/Environment/Negation.swift, Sources/HTMLKit/Framework/Environment/Nullable.swift, Sources/HTMLKit/Framework/Environment/Relation.swift, Sources/HTMLKit/Framework/Environment/Sequence.swift, Sources/HTMLKit/Framework/Environment/Statement.swift, Sources/HTMLKit/Framework/Extensions/Comparable+HTMLKit.swift, Sources/HTMLKit/Framework/Extensions/Datatypes+Content.swift, Sources/HTMLKit/Framework/Extensions/Optional+HTMLKit.swift, Sources/HTMLKit/Framework/Primitives/Elements/Element.swift, Sources/HTMLKit/Framework/Rendering/Renderer.swift, Sources/HTMLKitVapor/Extensions/Vapor+HTMLKit.swift, Tests/HTMLKitTests/EnvironmentTests.swift, Tests/HTMLKitVaporTests/ProviderTests.swift
This pull request adds statements to the environment allowing views to be shown based on conditional terms or to loop over a sequence within an environment context, while it is unfortunately not feasible with native statements.
```swift
Environment.check(user.loggedIn) {
Paragraph {
"True"
}
}
Environment.check(user.lastName == "Polo" && user.firstName == "Marco") {
Paragraph {
"True"
}
} then: {
Paragraph {
"False"
}
}
Environment.loop(user.roles) { role in
Paragraph {
role
}
}
Environment.unwrap(user.avatar) { avatar in
Image()
.source(avatar)
} then: {
Paragraph {
"No image found"
}
}
```
I also want to state that I am not completely satisfied with the naming yet and may change it in the future.
=> Extend the environment

Sources/HTMLKit/Framework/Rendering/Markdown/MarkdownString.swift, Tests/HTMLKitTests/RenderingTests.swift
This pull request experiments with helper functions for Markdown rendering that may be useful in the future.
```swift
MarkdownString("Vapor 5 will be \(bold: "awesome")!")
// is the equivalent to
MarkdownString("Vapor 5 will be **awesome**!")
```
- `\(italic: "Hello World")`
- `\(bold: "Hello World")`
- `\(strike: "Hello World")`
- `\(code: "<h1></h1>")`
- `\(link: "https://www.example.com")`
- `\(phone: "123-456-7890")`
- `\(email: "example@example.com")`
=> Add helper functions for markdown rendering

Sources/HTMLKit/Abstraction/Elements/BodyElements.swift, Sources/HTMLKit/Abstraction/Tokens/ValueTokens.swift
The type modifier of the `OrderedList` element should accept the marker enum. This pull request corrects that.
```swift
OrderedList {
}
.type(.lowercaseAlpha)
```
=> Make the type modifier of the orderedlist element accept the marker enum

Sources/HTMLKit/Abstraction/Attributes/BasicAttributes.swift, Sources/HTMLKit/Abstraction/Elements/BodyElements.swift, Tests/HTMLKitTests/AttributesTests.swift
The pull request adds the missing playsinline attribute. It is used on the video element to indicate that it should play inline instead of in fullscreen mode.
```swift
Video {
Source()
.source("...mp4")
.type(.mp4)
}
.playInline()
```
=> Introduce the playsinline attribute

.github/workflows/test.yml, Package.swift
This pull request drops support for Swift 5.8 and updates the dependencies.
=> Update the supported swift version

Sources/HTMLKit/Abstraction/Tokens/ValueTokens.swift, Tests/HTMLKitTests/AttributesTests.swift
This pull request adds the missing form method `dialog`.
```swift
Form()
.method(.dialog)
```
=> Add missing form method

Sources/HTMLKit/Abstraction/Attributes/BasicAttributes.swift, Sources/HTMLKit/Abstraction/Elements/BasicElements.swift, Sources/HTMLKit/Abstraction/Elements/BodyElements.swift, Sources/HTMLKit/Abstraction/Elements/DefinitionElements.swift, Sources/HTMLKit/Abstraction/Elements/FigureElements.swift, Sources/HTMLKit/Abstraction/Elements/FormElements.swift, Sources/HTMLKit/Abstraction/Elements/HeadElements.swift, Sources/HTMLKit/Abstraction/Elements/HtmlElements.swift, Sources/HTMLKit/Abstraction/Elements/InputElements.swift, Sources/HTMLKit/Abstraction/Elements/ListElements.swift, Sources/HTMLKit/Abstraction/Elements/MapElements.swift, Sources/HTMLKit/Abstraction/Elements/MediaElements.swift, Sources/HTMLKit/Abstraction/Elements/ObjectElements.swift, Sources/HTMLKit/Abstraction/Elements/RubyElements.swift, Sources/HTMLKit/Abstraction/Elements/TableElements.swift, Tests/HTMLKitTests/AttributesTests.swift, Tests/HTMLKitTests/LocalizationTests.swift
Currently, only a few of the elements are localizable. However, there a some cases where you might want to localize the value of certain attributes e.g. `.title()`, `.value()`, `.placeholder()`, `.alternate()` and `.content()` as well. This pull request adds support for that.
It also adds support for verbatim content, in case someone has localization enabled but explicitly does not want the value to be translated.
```swift
Input()
.placeholder(verbatim: "Lorem ipsum....")
```
=> Make attributes localizable

Sources/HTMLKit/Framework/Localization/Localization.swift, Sources/HTMLKit/Framework/Rendering/Renderer.swift, Tests/HTMLKitTests/LocalizationTests.swift, Tests/HTMLKitTests/RenderingTests.swift, Tests/HTMLKitVaporTests/ProviderTests.swift
Currently, there is a bug: if the preferred language (coming from the accept-language header) is not available, an error is thrown, which should not happen, as the fallback language should be used instead. This pull-request fixes that.
It also ensures that the remaining errors are non-fatal, as suggested in #148.
=> Make localization errors non-fatal

Sources/HTMLKitComponents/Components/Button.swift, Sources/HTMLKitComponents/Components/Disclosure.swift, Sources/HTMLKitComponents/Components/Form.swift, Sources/HTMLKitComponents/Components/Link.swift, Sources/HTMLKitComponents/Extensions/Components+Input.swift, Sources/HTMLKitComponents/Primitives/DynamicType.swift, Tests/HTMLKitComponentsTests/Localization/fr/web.strings, Tests/HTMLKitComponentsTests/LocalizationTests.swift
Currently, only the `Text` component supports localization. However, many other components require similar support. This pull request adds it.
=> Make components localizable

Sources/HTMLKit/Framework/Rendering/Renderer.swift
The date rendering replaced the whole String instead of adding to the current String.
=> Fix rendering a Date
